### ISSUE TITLE
gather of 3d array broken

### ISSUE THREAD

**Issue by mcarmesin** [eth-cscs/ImplicitGlobalGrid.jl#101]
I'm running  IGG with ParallelStencils on four GPUs, such that the grid is split in x and y but not in z.
Initializing the local array 
```
ψ.= Data.Array([ (x>-.1) && (y>-.1) && (z>-.1) for x in X_loc, y in Y_loc, z in Z_loc]) 
```
and gathering with

ψ_nohalo = zeros(ComplexF64,nx-2, ny-2, nz-2);
ψ_nohalo .= Array(ψ[2:end-1,2:end-1,2:end-1])
Ψ = me==0 ? Array{ComplexF64,3}(undef, (nx-2)*dims[1],(ny-2)*dims[2],(nz-2)*dims[3]) : nothing
gather!(ψ_nohalo,Ψ)

I obtain the results of the plots
![Psi](https://github.com/user-attachments/assets/1ae37ed8-7862-4d3a-b263-08d37bc3af24)

In the yz plane the data are corrupted like there is some indexing wrong when putting together the data .

**Comment by luraess** [comment]
Thanks for reporting - we'll have a look.

**Comment by omlins** [comment]
Hi @mcarmesin , sorry for the delay in reply. Could you please try with `ImplicitGlobalGrid@0.14.0`? After that, a new gather version was introduced (the current version).

**Comment by mcarmesin** [comment]
I found the problem: in the y-z plot the the data were erroneously transposed, such that Plots.jl distorted the data while plotting. 

Sorry for bothering with my stupidity.

**Comment by luraess** [comment]
Glad you figured out what was causing the issue. Thanks

**Comment by omlins** [comment]
> I found the problem: in the y-z plot the the data were erroneously transposed, such that Plots.jl distorted the data while plotting.
> 
> Sorry for bothering with my stupidity.

No problem. Happy to hear that it works now.
