### ISSUE TITLE
Update Halo for Higher dimension Tensors?

### ISSUE THREAD

**Issue by tianshu-wang** [eth-cscs/ImplicitGlobalGrid.jl#15]
Sometimes there are a lot tensors whose halos need be updated. Is it possible to update the halo of a higher dimension tensor A with size {nx, ny, nz, m}, where nx, ny, nz  are the size of grids?

I know it is equivalent to update_halo!(A_1, A_2, ..., A_m). Just want to know if it can be done more easily when m is a large number.

Thank you in advance!

**Comment by omlins** [comment]
Thanks for reporting this issue; that's a good point! 

How about splatting the 3-D sub-arrays into `update_halo!` by doing something like
```julia
update_halo!([A[:,:,:,i] for i=1:size(A,4)]...)
```
?

For clarity, here you see a working example of splatting 1-D sub-arrays into the the function `+`:
```julia
julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> [A[:,i] for i=1:size(A,2)]
2-element Vector{Vector{Int64}}:
 [1, 3]
 [2, 4]

julia> +([A[:,i] for i=1:size(A,2)]...)
2-element Vector{Int64}:
 3
 7
```

If you use this repeatedly, you could make a macro that does that array comprehension and splatting for you...

This solution makes of course only sense if `m` is not small else it is easier to write it explicitly as you did. We will think about the possibility to handle this and similar cases automatically inside `update_halo!`. That will certainly improve readability for cases like yours.

**Comment by omlins** [comment]
Thanks for reporting this issue; that's a good point!

If you use a vector of 3-D arrays to store your tensor `A`, then the solution is straightforward: you can simply splat the `m` 3-D arrays into `update_halo!`. Here is a minimal 2-D example (1 process, periodic boundaries):


```julia
julia> using ImplicitGlobalGrid

julia> init_global_grid(3, 3, 1, periodx=1, periody=1);
Global grid: 1x1x1 (nprocs: 1, dims: 1x1x1)

julia> A = [[1 2; 3 4; 5 6], [7 8 9; 10 11 12]]
2-element Vector{Matrix{Int64}}:
 [1 2; 3 4; 5 6]
 [7 8 9; 10 11 12]

julia> update_halo!(A...)

julia> A
2-element Vector{Matrix{Int64}}:
 [3 4; 3 4; 3 4]
 [8 8 8; 11 11 11]
```

Does that seem a good solution for you?

**Comment by tianshu-wang** [comment]
Yes! Thank you very much!
