### ISSUE TITLE
Unexpected halo behavior

### ISSUE THREAD

**Issue by smillerc** [eth-cscs/ImplicitGlobalGrid.jl#17]
I'm attempting to port a Fortran finite volume CFD code over to Julia and use ImplicitGlobalGrid as part of it. I'm having a bit of a hard time following the behavior of this package and need a few pointers. 

If I have a vector `A = [1, 2, 3, 4, 5, 6, 7, 8]` with periodic BCs and want to exchange the 2 halo elements on either side (where `[1, 2]` and `[7, 8]` are the halo elements). 
```julia
julia> using ImplicitGlobalGrid

julia> init_global_grid(8,1,1,periodx=1)
Global grid: 6x1x1 (nprocs: 1, dims: 1x1x1)
(0, [1, 1, 1], 1, [0, 0, 0], MPI.Comm(-2080374784))

julia> A = collect(1:8)
8-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8

julia> update_halo!(A)

julia> A
8-element Vector{Int64}:
 7
 2
 3
 4
 5
 6
 7
 2
```

This only swaps out 1 element, even though the overlap is 2. After running `update_halo!(A)`, I'm expecting it to turn into `A = [5, 6, 3, 4, 5, 6, 3, 4]` but it doesn't. What am I missing?

**Comment by luraess** [comment]
Hi @smillerc, thanks for your interests in ImplicitGlobalGrid (IGG) !

Taking your example, a 1D array of regular size `nx=8` such `A=[1, 2, 3, 4, 5, 6, 7, 8]` has `A[1, end]` as boundary points and `A=[2:end-1]` as inner points.

- Non periodic case:
  Assume we have a second array `B=[9, 10, 11, 12, 13, 14, 15, 16]` such that the global domain `D=[A, B]` (with some overlap), the overlap of 2 as defined in IGG by default implies following domain overlap:
  ```julia
  [1, 2, 3, 4, 5, 6, 7, 8 ]
                     |  |
                    [9, 10, 11, 12, 13, 14, 15, 16]
  ```
  thus the last inner point from `A` (`A[end-1]=7`) will be set as boundary point in `B` (`B[1]`) and by analogy `A[end]` will be replaced by `B[2]`. The global grid will thus be `D=[1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16]` and global `nx`: `nx_g = (nx-2)*2 + 2 = 14`.

- The periodic case:
  If now `A` is periodic, this means that following the above logic and overlap of 2, we have
  ```julia
  ... 5, 6, 7, 8]
            |  |
           [1, 2, 3, 4, ...
  
  ```
  where `A[end]` will be replaced by `A[2]`, and `A[1]` should be replaced by `A[end-1]`, resulting in the following global grid `D=[7, 2, 3, 4, 5, 6, 7, 2]` as returned by IGG. The arguments `overlapx`, `overlapy` and `overlapz` enable you to specify larger overlaps (type `?init_global_grid` for more details).

**Comment by smillerc** [comment]
@luraess Thank you for the explanation! One more thing. Is it possible to set the inner domain to be padded by 2 elements instead of 1, e.g. `A[1:2]` and `A[end-1:end]` and have the inner elements be `A[3:end-2]`, so that more than one element/cell/etc... gets swapped during the halo update?

**Comment by omlins** [comment]
Hi @smillerc, unfortunately, it is currently not possible to update a halo of width > 1. Adding support for a halo of width > 1 is definitively something on the radar (note yet done as we haven't had a use case that required it). However, it shouldn't be very difficult to add support for it and could be implemented in the near future.
