### ISSUE TITLE
MPI is already initialized, finalize_global_grid() doesn't finalizes

### ISSUE THREAD

**Issue by Eure-L** [eth-cscs/ImplicitGlobalGrid.jl#36]
Hi, 
I am trying to do multiple runs run in a for loop increasing the grid size over each iteration.
So I initialize the global grid at the start of the loop as such `init_global_grid(nx, ny, 1; init_MPI=true);` 
and make sure to finalize the global grid at the end    `finalize_global_grid(;finalize_MPI=true);`
but it always crashes on the second itteration
> `ERROR:` LoadError: MPI is already initialized. Set the argument 'init_MPI=false'

Setting the argument didn't help so I checked aftter the finalize call and found out `finalize_global_grid()`  didn't actually finalize MPI.

Am I doing it the wrong way, or is it impossible to launch multiple times a MPI task?
Also it might be possible that it comes from MPI.jl but am not sure so I post it there.

**Comment by omlins** [comment]
Hi @Eure-L,
MPI does not allow you to initialize and finalize multiple times in the same process, if this is what you're trying to do. This is not a limitation of ImplicitGlobalGrid.jl nor MPI.jl; it is given by the MPI standard.
 If you are doing this for loop directly in julia, then you could call [`MPI.Init`](https://juliaparallel.org/MPI.jl/stable/environment/#MPI.Init) and `MPI.Finalize` yourself and tell `ImplicitGlobalGrid` not to do it by setting the corresponding keyword arguments (as also partly explained [here](https://github.com/eth-cscs/ImplicitGlobalGrid.jl#seamless-interoperability-with-mpijl)):
 ```julia
 using ImplicitGlobalGrid
 import MPI
MPI.Init()
#(...)
 for ...
     init_global_grid(nx, ny, 1; init_MPI=false)
     #(... - your applications using ImplicitGlobalGrid) 
     finalize_global_grid(;finalize_MPI=false)
 end
MPI.Finalize()
```

**Comment by Eure-L** [comment]
Thank you very much @omlins ! I didn't thought of that.
This is such a shame though, having to deal with the JIT overhead for each time you want to launch a MPI process... When running large simulations it won't matter very much anymore I guess...
Sorry for this off topic issue, Ill close the issue now.

Thanks!

**Comment by omlins** [comment]
> JIT overhead for each time you want to launch a MPI process... 

I have the feeling I wasn't quite quite clear. What I noted as `#(... - your applications using ImplicitGlobalGrid)`, I imagined as the content of your original application or a function call (`your_application(...)`), not as a call to the shell. Then, this won't add any overhead compared to your original application.
