### ISSUE TITLE
Install size grows from 89M (released) to 535M (master)

### ISSUE THREAD

**Issue by mkitti** [eth-cscs/ImplicitGlobalGrid.jl#41]
The currently released version of ImplicitGlobalGrid.jl v0.1 currently installs 72 dependencies taking 89 megabytes of space in a clean Julia depot.

```
$ export JULIA_DEPOT_PATH=`mktemp -d`; julia -e 'using Pkg; Pkg.add("ImplicitGlobalGrid")' && du -hcs $JULIA_DEPOT_PATH/*
...
  72 dependencies successfully precompiled in 74 seconds
20M	/tmp/tmp.VnWvq05cMG/artifacts
36M	/tmp/tmp.VnWvq05cMG/compiled
32K	/tmp/tmp.VnWvq05cMG/environments
16K	/tmp/tmp.VnWvq05cMG/logs
29M	/tmp/tmp.VnWvq05cMG/packages
4.0K	/tmp/tmp.VnWvq05cMG/prefs
5.0M	/tmp/tmp.VnWvq05cMG/registries
24K	/tmp/tmp.VnWvq05cMG/scratchspaces
89M	total
```

The master branch after #34 expands this footprint to 95 dependencies taking 535 megabytes of space in a clean Julia depot.

```
$ export JULIA_DEPOT_PATH=`mktemp -d`; julia -e 'using Pkg; Pkg.add(name="ImplicitGlobalGrid", rev="master")' && du -hcs $JULIA_DEPOT_PATH/*
...
  95 dependencies successfully precompiled in 83 seconds (14 already precompiled)
450M	/tmp/tmp.kVz3DOLI0s/artifacts
7.1M	/tmp/tmp.kVz3DOLI0s/clones
41M	/tmp/tmp.kVz3DOLI0s/compiled
40K	/tmp/tmp.kVz3DOLI0s/environments
20K	/tmp/tmp.kVz3DOLI0s/logs
33M	/tmp/tmp.kVz3DOLI0s/packages
4.0K	/tmp/tmp.kVz3DOLI0s/prefs
5.0M	/tmp/tmp.kVz3DOLI0s/registries
32K	/tmp/tmp.kVz3DOLI0s/scratchspaces
535M	total
```

I found this while exploring https://github.com/omlins/CellArrays.jl/issues/16#issuecomment-1218371185, and I also wanted to document this here. My suggestion there was to split the core code into a small subdirectory package with fewer dependencies, then add that as a dependency of the main package.

**Comment by luraess** [comment]
The increase in size is mostly due to the fact that #master branch has now AMDGPU.jl as deps to support ROCm MPI. As you reported elsewhere, AMDGPU.jl is a large package as ships many jll.

**Comment by omlins** [comment]
Thanks for investigating this. As you found that it the AMDGPU.jl package that makes uses up most of the space  (reported on the other issue you mentioned), please open an issue there instead. I am closing this one therefore.

**Comment by omlins** [comment]
@mkitti : UPDATE:  we have removed the explicit GPU dependencies here making use of extensions; see the release notes of the latest release: https://github.com/eth-cscs/ImplicitGlobalGrid.jl/releases/tag/v0.15.0

This solves also the issue you brought up here completely.
