### ISSUE TITLE
Support MPI 0.20

### ISSUE THREAD

**Issue by vchuravy** [eth-cscs/ImplicitGlobalGrid.jl#46]
Currently IGG is holding back MPI.jl to 0.19 https://github.com/eth-cscs/ImplicitGlobalGrid.jl/blob/81fa7f90fd50e77759f5140fd4b9e4fc2f5399bf/Project.toml#L10

**Comment by luraess** [comment]
This PR https://github.com/eth-cscs/ImplicitGlobalGrid.jl/pull/42 will address it. We are waiting on some changes in AMDGPU.jl to finalise it.

**Comment by luraess** [comment]
This PR https://github.com/eth-cscs/ImplicitGlobalGrid.jl/pull/42 will address it. We are waiting on some changes in AMDGPU.jl to finalise it.

**Comment by luraess** [comment]
This will is resolved upon merging #55
