### ISSUE TITLE
Question/clarification: How fast this pacakge is it compared to CUDA.jl

### ISSUE THREAD

**Issue by sheevy** [eth-cscs/ImplicitGlobalGrid.jl#47]
I wanted to start using ImplicitGlobalGrids and ParallelStencil, but I got confused about the following statement from the docs:

> The simulation producing this movie - including the in-situ visualization - took 29 minutes on 8 NVIDIA® Tesla® P100 GPUs on Piz Daint (an optimized solution using [CUDA.jl](https://github.com/JuliaGPU/CUDA.jl)'s native kernel programming capabilities can be more than 10 times faster).

Does this mean that CUDA.jl can be 10 times faster that ImplicitGlobalGrids and ParallelStencil? Or am I misunderstanding it?

**Comment by luraess** [comment]
Sorry for the confusion. ImplicitGlobalGrid handles distributed memory parallelisation "only". As such, you are free to write the stencil operations using e.g. `CuArray` or `Array` broadcasting (as done in the exemples in the doc) or use another package such as e.g. ParallelStencil. The doc suggests that using a kernel programming approach (such as available in ParallelStencil) may result in a more than 10x speedup. 

> Does this mean that CUDA.jl can be 10 times faster that ImplicitGlobalGrids and ParallelStencil? Or am I misunderstanding it?

No, this means that using CUDA backend in ParallelStencil may be about 10 times faster than using `CuArray` broadcasting.

_Note: the timing reported in the [in-situ visu doc section](https://github.com/eth-cscs/ImplicitGlobalGrid.jl#straightforward-in-situ-visualization--monitoring) may be bound by gif / mp4 generation (reason why CPU and GPU timings are similar) and thus need to be adapted for usage in a production code._

**Comment by sheevy** [comment]
Thank you very much for clarification.

_Regarding note: yes, having to copy the data to plot it will be slow. There are some works/hacks to pass GPU allocated arrays directly to GLMakie: https://discourse.julialang.org/t/cuarray-glmakie/52461_

**Comment by omlins** [comment]
> Note: the timing reported in the [in-situ visu doc section](https://github.com/eth-cscs/ImplicitGlobalGrid.jl#straightforward-in-situ-visualization--monitoring) may be bound by gif / mp4 generation (reason why CPU and GPU timings are similar) and thus need to be adapted for usage in a production code.

@sheevy , @luraess Note that I have carefully designed these examples such that the overhead for visualization is negligible! This is achieved by generating an image only every one 1000th iteration.

> Regarding note: yes, having to copy the data to plot it will be slow.

@sheevy  compared to one thousand iterations it is negligible.

> The doc suggests that using a kernel programming approach (such as available in ParallelStencil) may result in a more than 10x speedup.

@sheevy  The reason why ParallelStencil is not mentioned here is simply that it did not yet exist when this documentation was written. We will soon revise the documentation globally and at such kind of information.
