### ISSUE TITLE
Support for CUDA.jl 4.0

### ISSUE THREAD

**Issue by LaurentPlagne** [eth-cscs/ImplicitGlobalGrid.jl#50]
Is it planned to support new version of CUDA.jl ?

**Comment by luraess** [comment]
Yes, it's WIP. We are in the process of making ImplicitGlobalGrid compatible with latest MPI.jl and support AMDGPU.jl as GPU-aware implementation.

**Comment by LaurentPlagne** [comment]
Cool !
A small drawing with Makie.jl as a super modest contribution (from a presentation of our use of ImplicitGlobalGrid.jl). 
You can find and play with the source here https://git.triscale-innov.com/TriScale/MakieDrawings
![split_grid](https://github.com/eth-cscs/ImplicitGlobalGrid.jl/assets/24976886/f945f14a-a7ac-4bfd-9703-b7d747fc6ac1)

**Comment by omlins** [comment]
@LaurentPlagne : thanks for sharing this! However, when I follow your link I get a page with a 404 error.

**Comment by LaurentPlagne** [comment]
Sorry... Is it better ?

https://github.com/triscale-innov/MakieDrawings.jl/tree/master

**Comment by luraess** [comment]
Is addressed in #55
